### PR TITLE
fix shebang

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by mcocdawc** [comment]
Thank you for your work.

I don't know if the `-tt` is actually required or not.
Since we need the templating system for the compilation I would like to let your Pull Requests run through our test suite.
Since this GitHub repo is just a mirror of our closed repo on BitBucket, could you please pass me your BitBucket account and I'll add you there.

Are you the author of [this paper](https://pubs.rsc.org/en/content/articlelanding/2016/CP/C6CP04019E)?

**Comment by e-kwsm** [comment]
> Since this GitHub repo is just a mirror of our closed repo on BitBucket, could you please pass me your BitBucket account and I'll add you there.

https://bitbucket.org/e-kwsm/ is my account.

> Are you the author of [this paper](https://pubs.rsc.org/en/content/articlelanding/2016/CP/C6CP04019E)?

Yes. That is my first journal publication :)

**Comment by mcocdawc** [comment]
Great, thank you very much. I just sent an invitation to your e-mail.

Congratulations!

I will close the PRs here in order to have them in the testsuite on BitBucket.

**Comment by e-kwsm** [comment]
I did’nt receive an invitation, probably because my email address was not public on bitbucket. Would you resend it to me?

**Comment by mcocdawc** [comment]
Hmm, that's strange. I sent it out.
Could you perhaps send me the e-mail address that is connected to your BitBucket account?

**Comment by e-kwsm** [comment]
My email address is e.kawaschima+bitbucket@gmail.com

**Comment by mcocdawc** [comment]
Ok, I sent it out to that address. Just let me know if there are any problems.

**Comment by e-kwsm** [comment]
Thank you, I have participated in the project.

**Comment by mcocdawc** [comment]
Just that we can communicate differently than publicly here.
My e-mail address is `oskar.weser@gmail.com`.

It would be great, if you could make the pull request into the branch `devel`.

(We regularly merge it into `master` and `stable` and publish them to the GitHub repo.)

**Pull request closed without merging**
